"""Adds repostories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/reboot-dev/respect repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of respect follow the Bazel build
# instructions at https://github.com/reboot-dev/respect.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@com_github_3rdparty_eventuals//bazel:repos.bzl", eventuals_repos = "repos")
load("@com_github_reboot_dev_pyprotoc_plugin//bazel:repos.bzl", pyprotoc_plugin_repos = "repos")

def repos(repo_mapping = {}):
    """Adds external repositories/archives needed by respect (phase 1).

    Args:
        repo_mapping: passed through to all other functions that expect/use
            repo_mapping, e.g., 'eventuals_repos'
    """

    # Official Python rules for Bazel.
    maybe(
        http_archive,
        name = "rules_python",
        sha256 = "9acc0944c94adb23fba1c9988b48768b1bacc6583b52a2586895c5b7491e2e31",
        url = "https://github.com/bazelbuild/rules_python/releases/download/0.27.0/rules_python-0.27.0.tar.gz",
        strip_prefix = "rules_python-0.27.0",
        repo_mapping = repo_mapping,
    )

    # Declare a specific gRPC version *first*, before eventuals have a chance
    # to define an alternative incompatible version.
    # TODO(Issue #644, Xander): Fix the compilation errors caused by combining newer
    # gRPC versions with `io_bazel_rules_go` repos (brought in via the
    # `io_bazel_rules_docker` repos).
    maybe(
        http_archive,
        name = "com_github_grpc_grpc",
        urls = ["https://github.com/grpc/grpc/archive/refs/tags/v1.45.0.tar.gz"],
        strip_prefix = "grpc-1.45.0",
        sha256 = "ec19657a677d49af59aa806ec299c070c882986c9fcc022b1c22c2a3caf01bcd",
    )

    pyprotoc_plugin_repos(
        repo_mapping = repo_mapping,
    )

    eventuals_repos(
        repo_mapping = repo_mapping,
    )

    maybe(
        http_archive,
        name = "io_bazel_rules_docker",
        sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
        # 0.25.0 is the latest release as of 2022/07/25.
        urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
        repo_mapping = repo_mapping,
    )

    maybe(
        http_archive,
        name = "rules_pkg",
        urls = [
            "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.5.1/rules_pkg-0.5.1.tar.gz",
            "https://github.com/bazelbuild/rules_pkg/releases/download/0.5.1/rules_pkg-0.5.1.tar.gz",
        ],
        sha256 = "a89e203d3cf264e564fcb96b6e06dd70bc0557356eb48400ce4b5d97c2c3720d",
        repo_mapping = repo_mapping,
    )

    maybe(
        git_repository,
        name = "googleapis",
        remote = "https://github.com/googleapis/googleapis",
        commit = "43c8e80a384841ec0f740e001f077d9af8a5eae8",
        shallow_since = "1668729854 -0800",
        repo_mapping = repo_mapping,
    )

    maybe(
        http_archive,
        name = "buildifier_prebuilt",
        sha256 = "ecef8f8c39eaf4f1c1604c677d232ade33818f898e35e7826e7564a648751350",
        strip_prefix = "buildifier-prebuilt-5.1.0.2",
        urls = [
            "http://github.com/keith/buildifier-prebuilt/archive/5.1.0.2.tar.gz",
        ],
    )

    maybe(
        http_archive,
        name = "mypy_integration",
        sha256 = "9d270fdb81e76fed1122a94c512b0930d70b837569dc488b58ab9c033641910d",
        strip_prefix = "bazel-mypy-integration-0.5.0",
        url = "https://github.com/bazel-contrib/bazel-mypy-integration/archive/refs/tags/0.5.0.tar.gz",
    )

    maybe(
        http_archive,
        name = "rules_proto",
        sha256 = "e017528fd1c91c5a33f15493e3a398181a9e821a804eb7ff5acdd1d2d6c2b18d",
        strip_prefix = "rules_proto-4.0.0-3.20.0",
        urls = [
            "https://github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0-3.20.0.tar.gz",
        ],
    )

    maybe(
        http_archive,
        name = "rules_buf",
        sha256 = "523a4e06f0746661e092d083757263a249fedca535bd6dd819a8c50de074731a",
        strip_prefix = "rules_buf-0.1.1",
        urls = [
            "https://github.com/bufbuild/rules_buf/archive/refs/tags/v0.1.1.zip",
        ],
    )

    maybe(
        http_archive,
        name = "com_github_facebook_rocksdb",
        url = "https://github.com/facebook/rocksdb/archive/refs/tags/v7.9.2.zip",
        sha256 = "ce7a498718df53b3a11f64578b283025c6cdd34bf7379a8e838b84eef212178c",
        strip_prefix = "rocksdb-7.9.2",
        # We apply a patch that removes the ability to use 'ccache'
        # because it may get found by cmake but not be usable within a
        # Bazel sandbox.
        patches = ["//bazel/rocksdb:do-not-use-ccache.patch"],
        patch_args = ["-p1"],
        build_file = "//bazel/rocksdb:rocksdb.BUILD",
    )

    maybe(
        http_archive,
        name = "io_bazel_rules_webtesting",
        sha256 = "e9abb7658b6a129740c0b3ef6f5a2370864e102a5ba5ffca2cea565829ed825a",
        urls = [
            "https://github.com/bazelbuild/rules_webtesting/releases/download/0.3.5/rules_webtesting.tar.gz",
        ],
    )

    # Using a specific commit to avoid a breaking change in the
    # `hermetic_cc_toolchain` repo suggested import way.
    # Using the '2.0.0' version, which is the latest version that
    # uses 'WORKSPACE' instead of 'MODULE' files.
    maybe(
        git_repository,
        name = "hermetic_cc_toolchain",
        remote = "https://github.com/uber/hermetic_cc_toolchain.git",
        commit = "9f2456cb09fc4be74621e6b84aecae44ce0530d5",
        shallow_since = "1685445262 +0300",
    )

    maybe(
        http_archive,
        name = "aspect_bazel_lib",
        sha256 = "e3151d87910f69cf1fc88755392d7c878034a69d6499b287bcfc00b1cf9bb415",
        strip_prefix = "bazel-lib-1.32.1",
        url = "https://github.com/aspect-build/bazel-lib/releases/download/v1.32.1/bazel-lib-v1.32.1.tar.gz",
    )
