//! `protoc` plugin support for concrete, unary Tonic forwarding adapters.
//!
//! This module deliberately generates one handler trait and adapter per protobuf
//! service. It does not infer Reboot method semantics or provide a dynamic Tonic
//! dispatcher.

use heck::ToSnakeCase;
use prost_types::compiler::{CodeGeneratorRequest, CodeGeneratorResponse, code_generator_response};
use prost_types::{FileDescriptorProto, MethodDescriptorProto, ServiceDescriptorProto};
use std::collections::BTreeMap;

const MODULE_PARAMETER_PREFIX: &str = "module=";

/// Generates concrete Tonic forwarding adapters for files selected by `protoc`.
///
/// The plugin accepts only `module=reboot_rust_schema::proto`. Methods must be
/// unary and their request/response messages must be top-level types in the
/// same protobuf package as the service file. Unsupported input is returned as
/// a plugin error instead of producing partial or invalid Rust.
pub fn generate(request: CodeGeneratorRequest) -> CodeGeneratorResponse {
    match generate_inner(request) {
        Ok(files) => CodeGeneratorResponse {
            file: files,
            ..Default::default()
        },
        Err(error) => CodeGeneratorResponse {
            error: Some(error),
            ..Default::default()
        },
    }
}

fn generate_inner(
    request: CodeGeneratorRequest,
) -> Result<Vec<code_generator_response::File>, String> {
    let module = request
        .parameter
        .as_deref()
        .and_then(|parameter| parameter.strip_prefix(MODULE_PARAMETER_PREFIX))
        .filter(|module| is_module_path(module))
        .ok_or_else(|| {
            "protoc-gen-reboot_rust requires a valid `module=<Rust path>` parameter".to_owned()
        })?;

    let descriptors: BTreeMap<_, _> = request
        .proto_file
        .iter()
        .filter_map(|file| file.name.as_deref().map(|name| (name, file)))
        .collect();

    request
        .file_to_generate
        .iter()
        .map(|name| {
            let file = descriptors
                .get(name.as_str())
                .ok_or_else(|| format!("missing descriptor for file_to_generate `{name}`"))?;
            generate_file(file, module)
        })
        .collect()
}

fn generate_file(
    file: &FileDescriptorProto,
    module: &str,
) -> Result<code_generator_response::File, String> {
    let file_name = required(&file.name, "file name")?;
    let package = required(&file.package, "protobuf package")?;
    if package.is_empty() {
        return Err(format!("file `{file_name}` has an empty protobuf package"));
    }

    let mut content = format!(
        "// @generated by protoc-gen-reboot_rust. Do not edit.\n\
         // Concrete unary forwarding adapters only; no Reboot runtime semantics are generated.\n\
         use {module} as proto;\n\n"
    );
    for service in &file.service {
        emit_service(&mut content, file_name, package, service)?;
    }

    Ok(code_generator_response::File {
        name: Some(output_name(file_name)?),
        content: Some(content),
        ..Default::default()
    })
}

fn emit_service(
    output: &mut String,
    file_name: &str,
    package: &str,
    service: &ServiceDescriptorProto,
) -> Result<(), String> {
    let service_name = required(&service.name, "service name")?;
    let handler_name = format!("{service_name}Handler");
    let adapter_name = format!("{service_name}Adapter");
    let server_module = format!("{}_server", snake_case(service_name));

    output.push_str("#[tonic::async_trait]\n");
    output.push_str(&format!(
        "pub trait {handler_name}: Send + Sync + 'static {{\n"
    ));
    for method in &service.method {
        let (method_name, request, response) =
            method_types(file_name, package, service_name, method)?;
        output.push_str(&format!(
            "    async fn {method_name}(\n        &self,\n        request: tonic::Request<proto::{request}>,\n    ) -> Result<tonic::Response<proto::{response}>, tonic::Status>;\n"
        ));
    }
    output.push_str("}\n\n");
    output.push_str(&format!(
        "pub struct {adapter_name}<H> {{\n    handler: H,\n}}\n\n"
    ));
    output.push_str(&format!(
        "impl<H> {adapter_name}<H> {{\n    pub fn new(handler: H) -> Self {{\n        Self {{ handler }}\n    }}\n}}\n\n"
    ));
    output.push_str("#[tonic::async_trait]\n");
    output.push_str(&format!(
        "impl<H: {handler_name}> proto::{server_module}::{service_name} for {adapter_name}<H> {{\n"
    ));
    for method in &service.method {
        let (method_name, request, response) =
            method_types(file_name, package, service_name, method)?;
        output.push_str(&format!(
            "    async fn {method_name}(\n        &self,\n        request: tonic::Request<proto::{request}>,\n    ) -> Result<tonic::Response<proto::{response}>, tonic::Status> {{\n        self.handler.{method_name}(request).await\n    }}\n"
        ));
    }
    output.push_str("}\n\n");
    Ok(())
}

fn method_types(
    file_name: &str,
    package: &str,
    service_name: &str,
    method: &MethodDescriptorProto,
) -> Result<(String, String, String), String> {
    let method_name = required(&method.name, "method name")?;
    if method.client_streaming.unwrap_or(false) || method.server_streaming.unwrap_or(false) {
        return Err(format!(
            "{file_name}: service `{service_name}` method `{method_name}` is streaming; only unary methods are supported"
        ));
    }
    let request = same_package_type(
        file_name,
        package,
        service_name,
        method_name,
        "request",
        &method.input_type,
    )?;
    let response = same_package_type(
        file_name,
        package,
        service_name,
        method_name,
        "response",
        &method.output_type,
    )?;
    Ok((snake_case(method_name), request, response))
}

fn same_package_type(
    file_name: &str,
    package: &str,
    service_name: &str,
    method_name: &str,
    kind: &str,
    value: &Option<String>,
) -> Result<String, String> {
    let type_name = required(value, "method type")?;
    let prefix = format!(".{package}.");
    let Some(name) = type_name.strip_prefix(&prefix) else {
        return Err(format!(
            "{file_name}: service `{service_name}` method `{method_name}` has {kind} type `{type_name}` outside package `{package}`"
        ));
    };
    if !is_identifier(name) {
        return Err(format!(
            "{file_name}: service `{service_name}` method `{method_name}` has unsupported {kind} type `{type_name}`; nested or invalid types are not supported"
        ));
    }
    Ok(name.to_owned())
}

fn output_name(file_name: &str) -> Result<String, String> {
    let Some(stem) = file_name.strip_suffix(".proto") else {
        return Err(format!("file `{file_name}` does not end in `.proto`"));
    };
    Ok(format!("{stem}.reboot.rs"))
}

fn required<'a>(value: &'a Option<String>, label: &str) -> Result<&'a str, String> {
    value
        .as_deref()
        .filter(|value| !value.is_empty())
        .ok_or_else(|| format!("missing {label}"))
}

fn is_identifier(value: &str) -> bool {
    let mut characters = value.chars();
    matches!(characters.next(), Some(character) if character == '_' || character.is_ascii_alphabetic())
        && characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

fn is_module_path(value: &str) -> bool {
    !value.is_empty() && value.split("::").all(is_identifier)
}

fn snake_case(value: &str) -> String {
    value.to_snake_case()
}

#[cfg(test)]
mod tests {
    use super::*;
    use prost_types::{FileDescriptorProto, MethodDescriptorProto, ServiceDescriptorProto};

    fn counter_request() -> CodeGeneratorRequest {
        CodeGeneratorRequest {
            parameter: Some("module=reboot_rust_schema::proto".to_owned()),
            file_to_generate: vec!["counter.proto".to_owned()],
            proto_file: vec![FileDescriptorProto {
                name: Some("counter.proto".to_owned()),
                package: Some("tests.reboot.protoc".to_owned()),
                service: vec![ServiceDescriptorProto {
                    name: Some("CounterWrites".to_owned()),
                    method: vec![MethodDescriptorProto {
                        name: Some("Increment".to_owned()),
                        input_type: Some(".tests.reboot.protoc.IncrementRequest".to_owned()),
                        output_type: Some(".tests.reboot.protoc.CounterValue".to_owned()),
                        ..Default::default()
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            }],
            ..Default::default()
        }
    }

    #[test]
    fn generates_concrete_unary_adapter() {
        let response = generate(counter_request());
        assert_eq!(response.error, None);
        assert_eq!(response.file.len(), 1);
        let file = &response.file[0];
        assert_eq!(file.name.as_deref(), Some("counter.reboot.rs"));
        let content = file.content.as_deref().unwrap();
        assert!(content.contains("pub trait CounterWritesHandler: Send + Sync + 'static"));
        assert!(content.contains("async fn increment("));
        assert!(
            content.contains(
                "proto::counter_writes_server::CounterWrites for CounterWritesAdapter<H>"
            )
        );
        assert!(content.contains("self.handler.increment(request).await"));
    }

    #[test]
    fn rejects_missing_or_invalid_module_parameter() {
        for parameter in [
            None,
            Some("module=other::9invalid".to_owned()),
            Some("not-module=downstream::wire".to_owned()),
        ] {
            let mut request = counter_request();
            request.parameter = parameter;
            let response = generate(request);
            assert!(response.file.is_empty());
            assert!(response.error.unwrap().contains("module=<Rust path>"));
        }
    }

    #[test]
    fn module_parameter_controls_the_generated_import() {
        let mut request = counter_request();
        request.parameter = Some("module=downstream::wire".to_owned());
        let content = generate(request).file.remove(0).content.unwrap();
        assert!(content.contains("use downstream::wire as proto;"));
    }

    #[test]
    fn snake_case_matches_protobuf_acronym_conventions() {
        assert_eq!(snake_case("APIService"), "api_service");
        assert_eq!(snake_case("GetURL"), "get_url");
    }

    #[test]
    fn rejects_streaming_and_external_types() {
        let mut streaming = counter_request();
        streaming.proto_file[0].service[0].method[0].client_streaming = Some(true);
        assert!(
            generate(streaming)
                .error
                .unwrap()
                .contains("only unary methods")
        );

        let mut external = counter_request();
        external.proto_file[0].service[0].method[0].input_type =
            Some(".other.Package.Request".to_owned());
        assert!(
            generate(external)
                .error
                .unwrap()
                .contains("outside package")
        );
    }
}
