load("@com_github_grpc_grpc//bazel:python_rules.bzl", "py_proto_library")
load("@com_github_reboot_dev_reboot//reboot:rules.bzl", "js_proto_library")
load("@com_google_protobuf//bazel:proto_library.bzl", "proto_library")

proto_library(
    name = "schema_proto",
    srcs = [":schema.proto"],
    visibility = ["//visibility:public"],
)

py_proto_library(
    name = "schema_py_proto",
    visibility = ["//visibility:public"],
    deps = [":schema_proto"],
)

js_proto_library(
    name = "schema_js_proto",
    package_json = ":package.json",
    proto = ":schema.proto",
    proto_deps = [":schema_proto"],
    visibility = ["//visibility:public"],
)
