"""
Tooling to help detect versioning issues with Reboot code.

NOTE: this module's exported interface MUST STAY BACKWARDS COMPATIBLE
      between releases; it is used by old generated Reboot code to
      detect versioning issues relative to newer Reboot libraries.
"""

import re
from reboot.aio.exceptions import InputError
from reboot.version import REBOOT_VERSION

# A released version is exactly `major.minor.patch`; development
# builds (e.g. the `//reboot:reboot.dev` Bazel target) may append a
# suffix to the release version they were built after.
_VERSION_PATTERN = re.compile(r'(\d+)\.(\d+)\.(\d+)(.*)', re.DOTALL)


def _parse_version(version: str) -> tuple[int, int, int, str]:
    """
    Parses `version` into its numeric components plus its (possibly
    empty) development suffix.
    """
    match = _VERSION_PATTERN.fullmatch(version)
    if match is None:
        raise ValueError(
            f"Version '{version}' must have exactly 3 parts "
            "(major.minor.patch), optionally followed by a development "
            "suffix"
        )
    return (
        int(match.group(1)),
        int(match.group(2)),
        int(match.group(3)),
        match.group(4),
    )


def version_less_than(version_a: str, version_b: str) -> bool:
    """
    Returns True if `version_a` is less than `version_b`.

    Compares version strings numerically by their components
    (major.minor.patch). A version may carry a suffix (e.g. a
    development build of the `//reboot:reboot.dev` Bazel target); such a
    build is made from source AFTER the release it is named for, so when
    the numeric components are equal the suffixed version is the higher
    one (any non-empty suffix naturally sorts after an empty one).
    Suffixes break ties between numerically identical versions by
    comparing lexicographically.

    An empty `version_a` is treated as the lowest possible version
    (always less than any non-empty version). This provides backwards
    compatibility for configurations that don't specify a version.

    Raises:
        ValueError: If either version doesn't start with exactly 3
        numeric parts (except empty `version_a`, which is allowed for
        backwards compatibility).
    """
    # Treat empty version_a as the lowest possible version.
    if not version_a:
        return bool(version_b)

    return _parse_version(version_a) < _parse_version(version_b)


def version_at_least(version: str, threshold_version: str) -> bool:
    """
    Returns True if `version` is at least `threshold_version`.
    """
    return not version_less_than(version, threshold_version)


class IncompatibleVersionError(InputError):
    """
    Raised when generated code is incompatible with the current Reboot library
    version.
    """


def check_generated_code_compatible(
    generated_code_reboot_version: str
) -> None:
    """
    Checks if code generated by the given Reboot version is compatible

    If this library is too new to work with the given Reboot version's generated
    code, an error is raised.

    Args:
        generated_code_reboot_version: The Reboot version of the generated code.
    """
    if REBOOT_VERSION != generated_code_reboot_version:
        raise IncompatibleVersionError(
            f"This code was generated for Reboot version "
            f"'{generated_code_reboot_version}', but the installed Reboot "
            f"version is '{ REBOOT_VERSION }'. Please run `rbt dev run` or "
            "`rbt generate` to regenerate this code."
        )
