load("@com_google_protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_python//python:defs.bzl", "py_library")
load("//reboot:rules.bzl", "py_reboot_library")

proto_library(
    name = "account_proto",
    srcs = [":account.proto"],
    deps = [
        "//rbt/v1alpha1:options_proto",
    ],
)

py_reboot_library(
    name = "account_py_reboot",
    proto = "account.proto",
    proto_library = ":account_proto",
    visibility = ["//tests/reboot/bdd:__subpackages__"],
)

py_library(
    name = "account_servicer_py",
    srcs = [":account_servicer.py"],
    srcs_version = "PY3",
    visibility = ["//tests/reboot/bdd:__subpackages__"],
    deps = [
        ":account_py_reboot",
        "//reboot/aio:contexts_py",
        "//reboot/aio/auth:authorizers_py",
    ],
)
