"""
Tooling to help detect versioning issues with Reboot code.

NOTE: this module's exported interface MUST STAY BACKWARDS COMPATIBLE
      between releases; it is used by old generated Reboot code to
      detect versioning issues relative to newer Reboot libraries.
"""

from rebootdev.aio.exceptions import InputError
from rebootdev.version import REBOOT_VERSION


def version_less_than(version_a: str, version_b: str) -> bool:
    """
    Returns True if `version_a` is less than `version_b`.

    Compares semantic version strings numerically by their components
    (major.minor.patch).

    An empty `version_a` is treated as the lowest possible version
    (always less than any non-empty version). This provides backwards
    compatibility for configurations that don't specify a version.

    Raises:
        ValueError: If either version doesn't have exactly 3 parts
        (except empty `version_a`, which is allowed for backwards
        compatibility).
    """
    # Treat empty version_a as the lowest possible version.
    if not version_a:
        return bool(version_b)

    parts_a = [int(x) for x in version_a.split('.')]
    parts_b = [int(x) for x in version_b.split('.')]

    if len(parts_a) != 3:
        raise ValueError(
            f"Version '{version_a}' must have exactly 3 parts (major.minor.patch)"
        )
    if len(parts_b) != 3:
        raise ValueError(
            f"Version '{version_b}' must have exactly 3 parts (major.minor.patch)"
        )

    return parts_a < parts_b


def version_at_least(version: str, threshold_version: str) -> bool:
    """
    Returns True if `version` is at least `threshold_version`.
    """
    return not version_less_than(version, threshold_version)


class IncompatibleVersionError(InputError):
    """
    Raised when generated code is incompatible with the current Reboot library
    version.
    """


def check_generated_code_compatible(
    generated_code_reboot_version: str
) -> None:
    """
    Checks if code generated by the given Reboot version is compatible

    If this library is too new to work with the given Reboot version's generated
    code, an error is raised.

    Args:
        generated_code_reboot_version: The Reboot version of the generated code.
    """
    if REBOOT_VERSION != generated_code_reboot_version:
        raise IncompatibleVersionError(
            f"This code was generated for Reboot version "
            f"'{generated_code_reboot_version}', but the installed Reboot "
            f"version is '{ REBOOT_VERSION }'. Please run `rbt dev run` or "
            "`rbt generate` to regenerate this code."
        )
