#!/bin/bash
#
# Installs a git pre-commit hook that runs the dev-tools and documentation
# pre-commit hooks. The generated hook resolves the repository location at
# RUNTIME (via `git rev-parse`), so it works wherever the repo is checked
# out — a devcontainer, a local clone, or a git worktree — instead of
# baking in the absolute path of wherever it happened to be installed.

function install_precommit_hook() {
    local repo_top_level
    repo_top_level="$(git rev-parse --show-toplevel)"

    # Hooks live in the common git dir, which is shared across worktrees.
    local hooks_dir
    hooks_dir="$(cd "$(git rev-parse --git-common-dir)" && pwd)/hooks"

    # In the mono repo, submodules live under `public/`; in the standalone
    # public repo they live directly at the top level.
    local prefix=""
    if [[ -d "${repo_top_level}/public" ]]; then
        prefix="public/"
    fi

    # Sanity-check that the source hooks exist (submodules must be checked
    # out) before installing.
    if [[ ! -f "${repo_top_level}/${prefix}submodules/dev-tools/pre-commit" ]]; then
        echo "Commit hook from dev-tools not found under '${prefix}submodules/dev-tools/'. Aborting."
        return 1
    fi
    if [[ ! -f "${repo_top_level}/${prefix}documentation/pre-commit" ]]; then
        echo "Commit hook from documentation not found under '${prefix}documentation/'. Aborting."
        return 1
    fi

    # Remove any previously-installed hooks, including the old symlink-based
    # layout that baked in absolute paths.
    rm -f "${hooks_dir}/dev-tools-pre-commit" \
          "${hooks_dir}/rbt-documentation-pre-commit" \
          "${hooks_dir}/pre-commit"

    # Write a self-contained hook that resolves the repo root (and thus the
    # submodule hook paths) at runtime. The single-quoted heredoc keeps the
    # `$(...)` and `${...}` literal so they are evaluated when the hook runs,
    # not now.
    cat >"${hooks_dir}/pre-commit" <<'HOOK'
#!/bin/bash
# Generated by .devcontainer/install_precommit_hook.sh — do not edit.
set -e
repo_top_level="$(git rev-parse --show-toplevel)"
prefix=""
[[ -d "${repo_top_level}/public" ]] && prefix="public/"
"${repo_top_level}/${prefix}submodules/dev-tools/pre-commit"
"${repo_top_level}/${prefix}documentation/pre-commit"
HOOK
    chmod +x "${hooks_dir}/pre-commit"
}

install_precommit_hook
