load("@rbt_pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "lua_py",
    srcs = [
        "lua.py",
    ],
    data = [
        ":add_header_x_reboot_application_id.lua.j2",
        ":compute_header_x_reboot_server_id.lua.j2",
        ":mangled_http_path.lua",
        ":remove_json_trailers.lua",
    ],
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [
        requirement("jinja2"),
    ],
)

py_library(
    name = "routing_filter_generator_py",
    srcs = [
        "routing_filter_generator.py",
    ],
    data = [
        "//reboot/templates:routing_filter.lua.j2",
    ],
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [
        ":lua_py",
        "//reboot/templates:tools_py",
        "@com_github_reboot_dev_reboot//rbt/v1alpha1:placement_planner_py_proto",
        "@com_github_reboot_dev_reboot//reboot/controller:servers_py",
    ],
)
