#!/bin/bash
#
# Fetches the shared workstation secrets from Google Secret Manager and
# writes them as `export` lines into a profile snippet that every shell
# sources, so they appear as environment variables in every terminal on
# the workstation.
#
# This runs automatically on every `devpod up` (via `postStartCommand` in
# `devcontainer.json`) on DevPod GCP workstations. It is a no-op anywhere
# without a GCE metadata server / service account, e.g. Codespaces or
# local Docker. It is safe to re-run by hand to pick up secret changes
# mid-session, after which you open a new shell:
#
#     .devcontainer/devpod/fetch-workstation-secrets.sh
#
# A secret is injected iff it carries the label `workstation-env=true`,
# and the secret's NAME becomes the environment variable name, so name
# secrets as valid shell identifiers (e.g. `OPENAI_API_KEY`). See the
# "Workstation secrets" section of `.devcontainer/README.md` for the
# `gcloud` commands to add/list/remove secrets and the one-time setup.

# Intentionally NOT `set -e`: a failure to fetch must never break
# workstation creation or a shell — secrets are best-effort.
set -uo pipefail

OUT=/etc/profile.d/10-workstation-secrets.sh
META="http://metadata.google.internal/computeMetadata/v1"
MFLAVOR=(-H "Metadata-Flavor: Google")

log() { echo "fetch-workstation-secrets: $*" >&2; }

# Bail quietly unless we're on a GCE VM (the metadata server answers).
if ! curl -sf -m 5 "${MFLAVOR[@]}" "$META/instance/name" >/dev/null 2>&1; then
  log "no GCE metadata server; skipping (expected off-GCP)."
  exit 0
fi

PROJECT="$(curl -sf -m 5 "${MFLAVOR[@]}" "$META/project/project-id" 2>/dev/null || true)"
TOKEN="$(curl -sf -m 5 "${MFLAVOR[@]}" \
  "$META/instance/service-accounts/default/token" 2>/dev/null \
  | python3 -c 'import sys,json; print(json.load(sys.stdin)["access_token"])' 2>/dev/null || true)"
if [ -z "${PROJECT:-}" ] || [ -z "${TOKEN:-}" ]; then
  log "no service-account token (is a service account attached?); skipping."
  exit 0
fi

# Do all the Secret Manager REST work in Python (stdlib only); it prints
# ready-to-source `export` lines. PROJECT/TOKEN come from the env.
script_dir="$(cd "$(dirname "$0")" && pwd)"
body="$(PROJECT="$PROJECT" TOKEN="$TOKEN" \
  python3 "$script_dir/fetch_workstation_secrets.py")"
if [ $? -ne 0 ]; then
  log "Secret Manager fetch failed; leaving existing secrets in place."
  exit 0
fi

# Write atomically as a profile snippet readable only by us and root.
tmp="$(mktemp)"
{
  echo "# Generated by .devcontainer/devpod/fetch-workstation-secrets.sh."
  echo "# Secrets in project '$PROJECT' labelled workstation-env=true. Do not edit."
  echo "$body"
} >"$tmp"
sudo install -m 0640 -o root -g "$(id -gn)" "$tmp" "$OUT"
rm -f "$tmp"

# `/etc/profile.d` is sourced by login shells; make sure interactive
# bash and zsh shells (e.g. VS Code terminals) pick it up too.
source_line=". $OUT  # workstation secrets"
for rc in /etc/bash.bashrc /etc/zsh/zshrc; do
  if [ -f "$rc" ] && ! sudo grep -qF "$OUT" "$rc"; then
    echo "[ -r $OUT ] && $source_line" | sudo tee -a "$rc" >/dev/null
  fi
done

log "wrote $(grep -c '^export ' "$OUT" 2>/dev/null || echo 0) secret(s) to $OUT"
