import jwt
import os
import reboot.aio.reboot
import time
import unittest
from reboot.aio.applications import Application
from reboot.aio.auth.token_verifiers import TokenVerifier
from reboot.aio.contexts import EffectValidation
from reboot.aio.external import InitializeContext
from reboot.aio.http import WebFramework
from reboot.aio.libraries import AbstractLibrary
from reboot.aio.reboot import ApplicationRevision
from reboot.aio.servicers import Servicer
from reboot.run_environments import in_nodejs
from reboot.settings import (
    ENVVAR_REBOOT_ENABLE_EVENT_LOOP_BLOCKED_WATCHDOG,
    ENVVAR_REBOOT_OAUTH_SIGNING_SECRET,
)
from typing import Any, Awaitable, Callable, Optional, Sequence, overload
from unittest import mock

# Hardcoded signing secret for unit tests. Not a real
# secret — only used in-process for test JWT minting.
_TEST_OAUTH_SIGNING_SECRET = "reboot-test-signing-secret"


def assert_called_twice_with(
    testcase: unittest.IsolatedAsyncioTestCase,
    mock_obj: mock.Mock,
    *args: Any,
    **kwargs: Any,
) -> None:
    """Asserts that the given mock received exactly two calls, and that they had
    the given arguments.

    This is a useful alternative to `Mock.assert_called_once_with` in the presence
    of effect validation, which will frequently trigger two identical calls to a mock.
    """
    call = mock.call(*args, **kwargs)
    mock_obj.assert_has_calls([call, call])
    testcase.assertEqual(mock_obj.call_count, 2)


class Reboot(reboot.aio.reboot.Reboot):
    """A testing specific version of `Reboot` that takes an `Application`
    instead of explicit keyword args."""

    def __init__(self) -> None:
        super().__init__(in_process=True)
        # Enable the event loop blocked watchdog for tests
        # so that blocking calls are detected early. This
        # must be set before `start()` which is where
        # `monitor_event_loop()` reads the env var.
        os.environ[ENVVAR_REBOOT_ENABLE_EVENT_LOOP_BLOCKED_WATCHDOG] = 'true'
        # Set a signing secret so that `OAuthServer` can be used in
        # tests without manual env patching. Mirrors what `rbt dev` does
        # for local development.
        os.environ[ENVVAR_REBOOT_OAUTH_SIGNING_SECRET] = (
            _TEST_OAUTH_SIGNING_SECRET
        )

    def make_valid_oauth_access_token(
        self,
        user_id: str = "test-user",
    ) -> str:
        """
        Mint a valid JWT OAuth access token for use in tests.
        
        The resulting token will be accepted by Reboot applications in
        unit tests, as if the caller had gone through the full OAuth
        flow and was authenticated with the given user ID.
        
        It doesn't matter which OAuth provider is used by the
        application; the OAuth flow doesn't in fact execute. A token is
        directly minted using the application's signing secret,
        emulating what happens in the final step of a successful OAuth
        flow. The resulting token is valid, but the identity it presents
        is just whatever the developer specified - no actual
        authentication takes place.
        """
        return self.make_jwt(
            type="access",
            sub=user_id,
            aud="reboot-mcp",
            # Valid for 1000 hours; much longer than any test should
            # ever run.
            exp=int(time.time()) + 60 * 60 * 1000,
        )

    def make_jwt(self, **claims: Any) -> str:
        """
        Mint an arbitrary JWT signed with the test signing secret.
        
        Use `make_bearer_token` for the common case of a valid access
        token; use this for custom tokens (expired, refresh, client,
        etc.).
        """
        return jwt.encode(
            claims,
            _TEST_OAUTH_SIGNING_SECRET,
            algorithm="HS256",
        )

    @overload
    async def up(
        self,
        application: Application,
        *,
        local_envoy: Optional[bool] = None,
        local_envoy_port: int = 0,
        local_envoy_tls: Optional[bool] = None,
        servers: Optional[int] = None,
        effect_validation: Optional[EffectValidation] = None,
    ) -> ApplicationRevision:
        ...

    @overload
    async def up(
        self,
        *,
        revision: Optional[ApplicationRevision] = None,
    ) -> ApplicationRevision:
        ...

    @overload
    async def up(
        self,
        *,
        servicers: list[type[Servicer]],
        # A legacy gRPC servicer type can't be more specific than `type`,
        # because legacy gRPC servicers (as generated by the gRPC `protoc`
        # plugin) do not share any common base class other than `object`.
        legacy_grpc_servicers: Optional[list[type]] = None,
        libraries: Sequence[AbstractLibrary] = [],
        web_framework: WebFramework,
        token_verifier: Optional[TokenVerifier] = None,
        initialize: Optional[Callable[[InitializeContext],
                                      Awaitable[None]]] = None,
        initialize_bearer_token: Optional[str] = None,
        local_envoy: Optional[bool] = None,
        local_envoy_port: int = 0,
        local_envoy_tls: Optional[bool] = None,
        servers: Optional[int] = None,
        effect_validation: Optional[EffectValidation] = None,
        revision: Optional[ApplicationRevision] = None,
    ) -> ApplicationRevision:
        ...

    async def up(
        self,
        application: Optional[Application] = None,
        *,
        servicers: Optional[list[type[Servicer]]] = None,
        # A legacy gRPC servicer type can't be more specific than `type`,
        # because legacy gRPC servicers (as generated by the gRPC `protoc`
        # plugin) do not share any common base class other than `object`.
        legacy_grpc_servicers: Optional[list[type]] = None,
        libraries: Sequence[AbstractLibrary] = [],
        web_framework: Optional[WebFramework] = None,
        token_verifier: Optional[TokenVerifier] = None,
        initialize: Optional[Callable[[InitializeContext],
                                      Awaitable[None]]] = None,
        initialize_bearer_token: Optional[str] = None,
        local_envoy: Optional[bool] = None,
        local_envoy_port: int = 0,
        local_envoy_tls: Optional[bool] = None,
        servers: Optional[int] = None,
        effect_validation: Optional[EffectValidation] = None,
        revision: Optional[ApplicationRevision] = None,
    ) -> ApplicationRevision:

        if revision is not None and application is not None:
            raise ValueError(
                "Only one of 'application' OR 'revision' can be passed"
            )

        if servicers is not None:
            raise ValueError("Not expecting 'servicers'")

        if legacy_grpc_servicers is not None:
            raise ValueError("Not expecting 'legacy_grpc_servicers'")

        if len(libraries) != 0:
            raise ValueError("Not expecting 'libraries'")

        if web_framework is not None:
            raise ValueError("Not expecting 'web_framework'")

        if token_verifier is not None:
            raise ValueError("Not expecting 'token_verifier'")

        if initialize is not None:
            raise ValueError("Not expecting 'initialize'")

        if initialize_bearer_token is not None:
            raise ValueError("Not expecting 'initialize_bearer_token'")

        if revision is not None:
            if servers is not None:
                raise ValueError("Not expecting 'servers'")

            if effect_validation is not None:
                raise ValueError("Not expecting 'effect_validation'")

            return await super().up(
                revision=revision,
            )

        if application is None:
            raise ValueError("Must pass one of 'application' or 'revision'")

        # Should only have `application`, `local_envoy`,
        # `local_envoy_port`, `servers`, `effect_validation`.

        # Check if application.http has methods or mounts (note this
        # isn't relevant for TypeScript, which doesn't have that
        # property). If yes, we need a local_envoy to be present to
        # handle these requests.
        if local_envoy is None and not in_nodejs():
            if application.has_http_routes_or_mounts():
                local_envoy = True

        # Mount MCP now that we know we have a real cluster coming up.
        # This is deliberately deferred from `Application.__init__`,
        # where the run environment was `InvalidRunEnvironment` (i.e.
        # no `rbt dev` / `rbt serve` process detected).
        application._mount_mcp(application._servicers or [])

        revision = await super().up(
            servicers=application.servicers,
            legacy_grpc_servicers=application.legacy_grpc_servicers,
            libraries=application.libraries,
            web_framework=application.web_framework,
            token_verifier=application.token_verifier,
            initialize=application.initialize,
            initialize_bearer_token=application._initialize_bearer_token,
            local_envoy=local_envoy,
            local_envoy_port=local_envoy_port,
            local_envoy_tls=local_envoy_tls,
            servers=servers,
            effect_validation=effect_validation,
        )

        return revision
