apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
    - port: {{ .Values.app.port }}
      name: public
  selector:
    app: {{ .Values.app.name }}
  type: LoadBalancer
