syntax = "proto3";

import "rbt/v1alpha1/options.proto";

package tests.reboot.protoc;

message TransactionCounter {
  option (rbt.v1alpha1.state) = {
    implements: ["tests.reboot.protoc.TransactionCounterWritesMethods"]
  };
  int64 value = 1;
}

message TransactionIncrementRequest {
  int64 amount = 1;
}

message TransactionCounterValue {
  int64 value = 1;
}

message TransactionLimitExceeded {
  int64 limit = 1;
}

service TransactionCounterWritesMethods {
  option (rbt.v1alpha1.service) = {
    state: "tests.reboot.protoc.TransactionCounter"
  };

  rpc Query(TransactionIncrementRequest) returns (TransactionCounterValue) {
    option (rbt.v1alpha1.method).reader = {};
  }

  rpc Apply(TransactionIncrementRequest) returns (TransactionCounterValue) {
    option (rbt.v1alpha1.method).writer = {};
  }

  rpc Increment(TransactionIncrementRequest) returns (TransactionCounterValue) {
    option (rbt.v1alpha1.method) = {
      transaction: { exclusive: {} }
      errors: ".tests.reboot.protoc.TransactionLimitExceeded"
    };
  }

  rpc FactoryIncrement(TransactionIncrementRequest) returns (TransactionCounterValue) {
    option (rbt.v1alpha1.method).transaction = {
      constructor: {}
      exclusive: {}
    };
  }

  rpc FactoryIncrementTarget(TransactionIncrementRequest) returns (TransactionCounterValue) {
    option (rbt.v1alpha1.method).transaction = {
      constructor: {}
      exclusive: {}
    };
  }

  rpc SharedRead(TransactionIncrementRequest) returns (TransactionCounterValue) {
    option (rbt.v1alpha1.method).transaction = {
      shared: {}
    };
  }
}
