[mypy]
python_version = 3.10
strict = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

# Import discovery.
mypy_path = backend/api:backend/src

[mypy-grpc.*]
ignore_missing_imports = true

[mypy-google.protobuf.*]
ignore_missing_imports = true
