/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  docsSidebar: [
    // { type: "autogenerated", dirName: "." },
    {
      type: "doc",
      id: "overview",
      label: "Overview",
    },
    {
      type: "category",
      collapsed: false,
      label: "Durable reactive backends",
      items: [
        {
          type: "category",
          collapsed: true,
          label: "Get started",
          items: [
            "get_started/typescript_backend",
            "get_started/python_backend",
            "get_started/react_frontend",
          ],
        },
        "get_started/examples",
        {
          type: "category",
          collapsed: true,
          label: "Docs",
          items: [
            {
              type: "category",
              collapsed: true,
              label: "Define your API",
              items: [
                "develop/define/overview",
                "develop/define/methods",
                "develop/define/zod",
                "develop/define/protobuf",
                "develop/define/pydantic",
              ],
            },

            {
              type: "category",
              collapsed: true,
              label: "Implement your API",
              items: [
                "develop/implement/servicers",
                "develop/implement/readers",
                "develop/implement/writers",
                "develop/implement/transactions",
                "develop/implement/workflows",
              ],
            },
            {
              type: "category",
              collapsed: true,
              label: "Call your API",
              items: [
                "develop/call/overview",
                "develop/call/from_react",
                // "develop/call/from_browser",
                "develop/call/from_within_your_app",
                "develop/call/from_outside_your_app",
                "develop/call/via_http",
              ],
            },
            "develop/applications",
            "develop/testing",
            "develop/auth",
            "develop/secrets",
            "develop/errors",
            "develop/tasks",
            "develop/side_effects",
            "develop/idempotency",
          ],
        },
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "Durable MCP",
      items: [
        {
          type: "category",
          collapsed: true,
          label: "Get started",
          items: ["get_started/typescript_mcp", "get_started/python_mcp"],
        },
      ],
    },
    {
      type: "category",
      collapsed: true,
      label: "Standard library",
      items: [
        "library_services/overview",
        "library_services/mailgun",
        "library_services/ordered_map",
        "library_services/pubsub",
        "library_services/queue",
        "library_services/sorted_map",
        "library_services/item",
        //     {
        //       type: "category",
        //       label: "Coming soon",
        //       items: [
        //         "library_services/coming_soon/list",
        //         "library_services/coming_soon/presence",
        //         "library_services/coming_soon/twilio",
        //         "library_services/coming_soon/stripe",
        //       ],
        //     },
        //     /* TODO: #3394.
        //     "library_services/how_to",
        //     */
      ],
    },
    {
      type: "doc",
      id: "develop_locally",
      label: "Develop locally",
    },
    "tools/cli",
    {
      type: "doc",
      id: "deploy_on_your_own",
      label: "Deploy on your own",
    },
    {
      type: "doc",
      id: "deploy_on_reboot_cloud",
      label: "Deploy on Reboot Cloud",
    },
    // {
    //   type: "category",
    //   label: "Deploy & operate",
    //   items: ["deploy_operate/where", "deploy_operate/import_export"],
    // },
    // TODO: #3363.

    {
      type: "doc",
      id: "known_issues",
      label: "Known issues",
    },
  ],
};

module.exports = sidebars;
