app:
  name: "hello"
  # TODO: Using a static image, rather than an image built from the base-image
  # on `main`.
  image: "ghcr.io/reboot-dev/reboot/examples/hello@sha256:b3420ac1507ac66f977b77ba65f1ed6264e229a9d1812b9801e7cbef11dbcb83"
  storage:
    existingStorageClass:
      # `k3d`'s local path storage.
      name: "local-path"
      storageRequest: "1Gi"
