app:
  name: "hello"
  # TODO: Using a static image, rather than an image built from the base-image
  # on `main`.
  image: "ghcr.io/reboot-dev/reboot/examples/hello@sha256:c81fbbb47b3466349a655adee2dfb21c9cd3ae1f11d294d183d46d776097b081"
  storage:
    existingStorageClass:
      # `k3d`'s local path storage.
      name: "local-path"
      storageRequest: "1Gi"
